name: Mini Blog CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest     # matlab github ek vm dega os hoga ubuntu ka latest version 

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      SUPABASE_URL: ${{ secrets.DATABASE_URL }}  # ${{}} github actions expressions syntax
      SUPABASE_KEY: ${{ secrets.DATABASE_KEY }}
      REDIS_URL: redis://localhost:6379

    steps:
      - uses: actions/checkout@v4    # "-" yaml me list items start hota hai, uses: koi prebuilt github actions use kar rahe ho, code clone ho raha hai ci vm machine pe 

      - uses: actions/setup-python@v5   # action python install karta hai 
        with:                           # configuration pass karte hai 
          python-version: "3.11"        # 3.11 install karega "" isi liye lagay taaki float na samajh le 

      - run: pip install -r requirements.txt   # command run karo -r means read from file or saari dependencies and all install karo 

      - run: pytest -v         #-v har test ka naam show karega pass faily clearly batayega 